'use strict';
// Nội dung và trạng thái chỉ thuộc module Khởi động chính.
const exercises = [
  { name:'Chạy quanh sân', icon:'🏃', dose:'2–3 vòng', xp:40, type:'laps', goals:['Tăng nhịp tim','Cải thiện sức bền'], steps:['Đứng tại vạch xuất phát, giữ thân người thẳng và thả lỏng vai.','Chạy quanh sân với nhịp vừa sức, phối hợp tay chân và thở đều.','Hoàn thành 2 hoặc 3 vòng theo lựa chọn; nghỉ giữa hai hiệp rồi lặp lại.'], errors:['Xuất phát quá nhanh','Gồng vai hoặc nín thở','Chạy sát, cắt ngang đường của bạn tập'] },
  { name:'Jumping Jack', icon:'🤸', dose:'20 lần', xp:30, reps:20, goals:['Toàn thân','Phối hợp tay chân'], steps:['Đứng thẳng, hai chân khép, hai tay thả dọc thân.','Bật mở chân sang hai bên, đồng thời đưa hai tay qua đầu.','Bật khép chân và hạ tay về tư thế đầu; một chu kỳ mở–khép là 1 lần. Thực hiện 20 lần mỗi hiệp.'], errors:['Tiếp đất quá mạnh','Tay chân không đồng bộ','Gối khóa cứng'] },
  { name:'Tay chạm chân (Đá lăng chân)', icon:'🦵', dose:'15 lần', xp:30, reps:15, goals:['Linh hoạt hông','Kéo giãn chân'], steps:['Đứng thẳng, hai chân mở tự nhiên, tay đưa ra trước ở độ cao thoải mái.','Nâng một chân về trước, đưa tay đối diện về phía mũi chân trong tầm với; không ép chạm nếu phải gập lưng.','Hạ chân nhẹ nhàng, đổi bên luân phiên. Mỗi lần nâng–hạ một chân tính là 1 lần; 15 lần mỗi hiệp, đổi chân bắt đầu ở hiệp 2.'], errors:['Cúi gập lưng để cố chạm chân','Đá quá cao hoặc giật mạnh','Mất thăng bằng khi đổi chân'] },
  { name:'Nhón gót chân', icon:'🦶', dose:'20 lần', xp:25, reps:20, goals:['Cơ bắp chân','Cổ chân'], steps:['Đứng hai chân rộng bằng hông, giữ thân người thẳng; có thể vịn nhẹ vào điểm tựa chắc chắn.','Nâng hai gót chân chậm rãi, dồn trọng lượng lên phần trước bàn chân.','Hạ gót có kiểm soát; nâng và hạ hoàn chỉnh tính là 1 lần. Thực hiện 20 lần mỗi hiệp.'], errors:['Nhún bật thay vì nâng chậm','Cổ chân đổ ra ngoài hoặc vào trong','Hạ gót đột ngột'] },
  { name:'Nâng cao đùi', icon:'🏃', dose:'30 lần', xp:40, reps:30, goals:['Tăng tốc độ chân','Kích hoạt cơ đùi'], steps:['Đứng thẳng, khuỷu tay co nhẹ, mắt nhìn về phía trước.','Luân phiên nâng gối tới độ cao vừa sức, đánh tay đối bên và tiếp đất nhẹ.','Mỗi lần nâng–hạ một chân tính là 1 lần; thực hiện 30 lần mỗi hiệp, giữ nhịp đều.'], errors:['Ngả thân quá nhiều ra sau','Dậm chân quá mạnh','Nâng gối quá sức, mất nhịp tay chân'] },
  { name:'Bật qua cọc/mốc', icon:'⬆️', dose:'1/2 sân', xp:50, type:'distance', goals:['Phản xạ','Sức bật'], steps:['Dùng mốc thấp, mềm hoặc chai nhựa rỗng; bố trí khoảng cách phù hợp trên đoạn nửa sân, kiểm tra mặt sân không trơn.','Hơi gập gối, phối hợp đánh tay và bật qua từng mốc thấp; tiếp đất nhẹ với gối mềm.','Hoàn thành đoạn nửa sân đã đánh dấu, nghỉ giữa hiệp rồi lặp lại. Thực hiện theo bố trí và hướng dẫn của giáo viên.'], errors:['Dùng mốc quá cao hoặc vật cứng','Tiếp đất với gối khóa cứng','Bật liên tiếp khi chưa giữ được thăng bằng'] }
];
const state = {
  view:'intro', index:0, restSeconds:30, laps:2, totalMs:0,
  items:exercises.map(()=>({sets:0,count:0,restMs:0,restTotalMs:0})),
  active:false, clock:0, checkpointMs:120000, checkpointStarted:false
};
const screen=document.querySelector('#screen');
let interval=null, toastTimer=null;
const item=()=>state.items[state.index];
const earnedXP=()=>exercises.reduce((sum,e,i)=>sum+(state.items[i].sets===2?e.xp:0),0);
const completedCount=()=>state.items.filter(e=>e.sets===2).length;
const setCount=()=>state.items.reduce((sum,e)=>sum+e.sets,0);
const pad=n=>String(n).padStart(2,'0');
const clockText=ms=>`${pad(Math.floor(Math.ceil(ms/1000)/60))}:${pad(Math.ceil(ms/1000)%60)}`;
const back=()=>'<button class="back" data-action="list">← Danh sách bài tập</button>';
function progress(){return `<div class="module-progress"><div><span>${completedCount()}/6 bài hoàn thành</span><b>${setCount()}/12 hiệp</b></div><progress max="12" value="${setCount()}" aria-label="Đã hoàn thành ${setCount()} trên 12 hiệp"></progress></div>`;}
function render(html){screen.innerHTML=html;document.querySelector('#earned').textContent=`${earnedXP()} / 215 XP`;window.scrollTo({top:0,behavior:'instant'});const h=screen.querySelector('h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}}
function intro(){stop();state.view='intro';render(`<a class="back" href="index.html">← Quay lại trang chủ</a><section class="intro-card"><div class="intro-symbol">⚡</div><span class="module-label">FITQUEST · GIAI ĐOẠN 02</span><h1>KHỞI ĐỘNG CHÍNH</h1><p class="subtitle">Chuẩn bị cơ thể trước buổi tập</p><p class="description">Tăng nhịp tim, kích hoạt cơ bắp, nâng cao nhiệt độ cơ thể và chuẩn bị cho phần tập luyện thể chất.</p><div class="intro-stats"><div><b>🔥 6 bài tập</b><span>2 hiệp mỗi bài</span></div><div><b>⏱ 10–15 phút</b><span>Thời lượng dự kiến</span></div><div><b>💪 Trung bình</b><span>Beginner → Intermediate</span></div></div><div class="rest-note">⏸ Nghỉ 30 giây – 1 phút giữa các hiệp<br>⭐ Chinh phục trọn bộ để nhận <b>215 XP</b></div><button class="primary" data-action="list">▶ BẮT ĐẦU KHỞI ĐỘNG CHÍNH</button><div class="route-strip"><b>01 · Chọn bài</b><span>02 · Tập & nghỉ</span><span>03 · Mốc 1</span></div></section>`);}
function restOptions(){return `<label class="rest-setting">⏱ Nghỉ giữa hiệp <select id="rest-select" aria-label="Thời gian nghỉ giữa hiệp">${[30,45,60].map(n=>`<option value="${n}" ${state.restSeconds===n?'selected':''}>${n} giây</option>`).join('')}</select></label>`;}
function list(){stop();state.view='list';render(`<button class="back" data-action="intro">← Giới thiệu module</button><section class="module-hero"><span class="module-label">GIAI ĐOẠN 02 · TẬP THEO HIỆP</span><h1>🔵 Khởi động chính</h1><p>6 động tác, 12 hiệp. Tập đúng nhịp, nghỉ đủ giữa các hiệp và cùng chạm mốc đầu tiên.</p><div class="module-tags"><span>▥ Beginner → Intermediate</span><span>⏱ Dự kiến 10–15 phút</span><span>⭐ Tổng 215 XP</span></div>${progress()}</section><div class="overview-line"><h2>Danh sách 6 bài tập</h2><span>${completedCount()}/6 hoàn thành</span></div>${restOptions()}<div class="exercise-list">${exercises.map((e,i)=>`<article class="exercise-card ${state.items[i].sets===2?'done':''}"><div class="exercise-top"><span class="sport-icon">${e.icon}</span><span class="exercise-number">${state.items[i].sets===2?'✓ HOÀN THÀNH':`BÀI ${pad(i+1)}`}</span></div><h3>${e.name}</h3><div class="exercise-meta-row"><div class="dose">${e.dose}<small>× 2 hiệp</small></div><span class="xp-pill">⭐ +${e.xp} XP</span></div><div class="set-dots">${[1,2].map(n=>`<span class="${state.items[i].sets>=n?'checked':''}">${state.items[i].sets>=n?'✓ ':''}Hiệp ${n}</span>`).join('')}</div><ul>${e.goals.map(g=>`<li>${g}</li>`).join('')}</ul><button class="detail-button" data-open="${i}">${state.items[i].restMs>0?'⏱ TIẾP TỤC NGHỈ':'CHI TIẾT →'}</button></article>`).join('')}</div><div class="launch-row"><button class="primary" data-action="continue">${completedCount()===6?'ĐẾN CHECKPOINT MỐC 1':'▶ TIẾP TỤC VỚI BÀI CHƯA HOÀN THÀNH'}</button></div>`);}
function detail(index){stop();state.index=index;if(item().restMs>0)return rest();state.view='detail';const e=exercises[index],s=item();render(`${back()}<div class="detail-heading"><span class="sport-icon">${e.icon}</span><div><span class="module-label">BÀI ${pad(index+1)}/06</span><h1>${e.name}</h1></div></div><div class="detail-grid"><div><motion-guide exercise="main-${index}"></motion-guide><section class="player"><div id="player-content"></div></section>${progress()}</div><section class="card instructions"><div class="params"><div><span>KHỐI LƯỢNG</span><strong>${e.dose}</strong></div><div><span>HIỆP</span><strong>${Math.min(s.sets+1,2)}/2</strong></div><div><span>NGHỈ</span><strong>${state.restSeconds} giây</strong></div></div><h2>Hướng dẫn động tác</h2><ol class="steps">${e.steps.map(t=>`<li>${t}</li>`).join('')}</ol><div class="mistakes"><h2>⚠ Lỗi thường gặp</h2><ul>${e.errors.map(t=>`<li>${t}</li>`).join('')}</ul></div></section></div>`);renderPlayer();}
function target(){return exercises[state.index].type==='laps'?state.laps:exercises[state.index].reps;}
function renderPlayer(){const root=document.querySelector('#player-content');if(!root)return;const e=exercises[state.index],s=item();if(s.sets===2){root.innerHTML=`<span class="player-status">✓ HOÀN THÀNH 2/2 HIỆP</span><div class="counter">+${e.xp}<span> XP</span></div><p class="phase">Đã ghi nhận, không cộng lại khi xem bài.</p><button class="primary" data-action="next">${completedCount()===6?'CHECKPOINT MỐC 1':'BÀI TIẾP THEO'} →</button>`;return;}
root.innerHTML=`<div class="player-status">HIỆP ${s.sets+1}/2 · ${state.active?'ĐANG TẬP':'SẴN SÀNG'}</div><div class="counter" id="counter">${e.type==='distance'?'½ <span>sân</span>':`${s.count}<span> / ${target()} ${e.type==='laps'?'vòng':'lần'}</span>`}</div><p class="phase" id="phase">${e.type==='distance'?'Hoàn thành đoạn nửa sân đã đánh dấu.':e.type==='laps'?'Bấm xác nhận khi kết thúc mỗi vòng sân.':`Một chuyển động trọn vẹn = 1 lần.${state.index===2?` Bắt đầu bằng chân ${s.sets===0?'trái':'phải'}.`:''}`}</p>${e.type==='laps'&&s.sets===0&&s.count===0&&!state.active?`<label class="rest-setting lap-setting">Mục tiêu mỗi hiệp <select id="lap-select">${[2,3].map(n=>`<option value="${n}" ${state.laps===n?'selected':''}>${n} vòng</option>`).join('')}</select></label>`:''}<div class="player-actions">${!state.active?'<button class="primary" data-action="start">▶ BẮT ĐẦU / TIẾP TỤC</button>':`<button class="primary" data-action="count">✓ ${e.type==='distance'?'ĐÃ XONG NỬA SÂN':e.type==='laps'?'XONG 1 VÒNG':'XÁC NHẬN 1 LẦN'}</button><button class="secondary" data-action="pause">⏸ TẠM DỪNG</button>`}</div><p class="player-hint">${e.type==='distance'?'Tự xác nhận sau khi hoàn thành quãng đường.':'Bạn hoặc bạn tập cùng xác nhận số lần trên màn hình.'} Sau hiệp 1, đồng hồ nghỉ tự bắt đầu.</p>`;}
function start(){if(state.active||item().sets===2||state.view!=='detail')return;state.active=true;state.clock=performance.now();interval=setInterval(tick,100);renderPlayer();}
function tick(){if(!state.active)return;const now=performance.now();let delta=Math.max(0,now-state.clock);state.clock=now;if(state.view==='rest'){delta=Math.min(delta,item().restMs);item().restMs=Math.max(0,item().restMs-delta);state.totalMs+=delta;updateRest();if(item().restMs===0){halt();announce('Đã hết giờ nghỉ. Sẵn sàng cho hiệp 2.');updateRest();}}else if(state.view==='checkpoint'){delta=Math.min(delta,state.checkpointMs);state.checkpointMs=Math.max(0,state.checkpointMs-delta);updateCheckpoint();if(state.checkpointMs===0){halt();announce('Đã hoàn thành 2 phút nghỉ mốc 1.');updateCheckpoint();}}else if(state.view==='detail'){state.totalMs+=delta;}}
function halt(){state.active=false;clearInterval(interval);interval=null;}
function stop(){if(state.active)tick();halt();}
function count(){if(state.view!=='detail'||!state.active||item().sets===2)return;tick();item().count++;if(exercises[state.index].type==='distance'||item().count>=target())finishSet();else document.querySelector('#counter').innerHTML=`${item().count}<span> / ${target()} ${exercises[state.index].type==='laps'?'vòng':'lần'}</span>`;}
function finishSet(){stop();item().sets++;item().count=0;if(item().sets===1){item().restMs=state.restSeconds*1000;item().restTotalMs=item().restMs;return rest(true);}const e=exercises[state.index];state.view='complete';render(`${back()}<section class="completion"><div class="celebrate">🎉</div><span class="module-label">TRỌN VẸN 2 HIỆP!</span><h1>Hoàn thành ${e.name}</h1><div class="reward">⭐ +${e.xp} XP</div><p>Thêm một thử thách được chinh phục.</p>${progress()}<button class="primary" data-action="next">${completedCount()===6?'ĐẾN CHECKPOINT MỐC 1':'BÀI TIẾP THEO'} →</button></section>`);}
function rest(autoStart=false){stop();state.view='rest';render(`${back()}<section class="rest-screen"><span class="module-label">HIỆP 1/2 ĐÃ HOÀN THÀNH</span><h1>⏱ Nghỉ giữa hiệp</h1><div class="rest-dial" id="rest-dial"><div><strong id="rest-clock"></strong><small>NGHỈ PHỤC HỒI</small></div></div><div class="rest-copy">Thả lỏng cơ thể<br>Uống nước nếu cần</div><div class="up-next">TIẾP THEO<b>${exercises[state.index].name} · Hiệp 2/2</b></div><button class="primary" id="rest-continue" data-action="rest-continue">TIẾP TỤC →</button><button class="secondary" id="rest-pause" data-action="rest-toggle"></button><p class="timer-announcement" id="timer-announcement" role="status"></p></section>`);if(autoStart)startRest();updateRest();}
function startRest(){if(state.active||item().restMs<=0)return;state.active=true;state.clock=performance.now();interval=setInterval(tick,100);updateRest();}
function updateRest(){if(state.view!=='rest')return;document.querySelector('#rest-clock').textContent=clockText(item().restMs);document.querySelector('#rest-dial').style.setProperty('--arc',`${item().restMs/Math.max(1,item().restTotalMs)*100}%`);document.querySelector('#rest-continue').disabled=item().restMs>0;const button=document.querySelector('#rest-pause');button.hidden=item().restMs===0;button.textContent=state.active?'⏸ TẠM DỪNG ĐỒNG HỒ':'▶ TIẾP TỤC ĐỒNG HỒ';}
function next(){if(completedCount()===6)return checkpoint();let i=state.items.findIndex((s,i)=>i>state.index&&s.sets<2);if(i<0)i=state.items.findIndex(s=>s.sets<2);detail(i);}
function checkpoint(){if(completedCount()!==6)return list();stop();state.view='checkpoint';const seconds=Math.floor(state.totalMs/1000);render(`<a class="back" href="index.html">← Về trang chủ</a><section class="completion checkpoint-screen"><div class="celebrate">🏁</div><span class="module-label">CHECKPOINT · MỐC 1</span><h1>HOÀN THÀNH<br>KHỞI ĐỘNG</h1><p>Bạn đã hoàn thành phần khởi động chính!</p><div class="reward">⭐ +215 XP</div><div class="result-grid"><div><span>✅ Bài tập</span><strong>6/6</strong></div><div><span>⏱ Thời gian thực tế*</span><strong>${Math.floor(seconds/60)}:${pad(seconds%60)}</strong></div></div><div class="reward-breakdown">🔥 <b>Streak +1</b> · Minh họa, chưa ghi vào hồ sơ</div><p class="stop-note">*Phút:giây, gồm thời gian tập và nghỉ giữa hiệp.<br>Dự kiến 10–15 phút; chưa gồm 2 phút nghỉ mốc 1.</p><section class="checkpoint-rest"><h2>⏸ NGHỈ MỐC 1 · 2 PHÚT</h2><p>💧 Uống 2–3 ngụm nước nhỏ</p><div class="checkpoint-clock" id="checkpoint-clock">02:00</div><progress id="checkpoint-progress" max="120000" value="0" aria-label="Tiến độ nghỉ mốc 1"></progress><button class="secondary" id="checkpoint-toggle" data-action="checkpoint-toggle"></button><p class="timer-announcement" id="timer-announcement" role="status"></p></section><div class="next-module">CHUẨN BỊ CHUYỂN SANG<strong>PHẦN THỂ CHẤT & THANG DÂY</strong>10 bài tập · Thể chất cơ bản & Thang dây.</div><button class="primary" id="checkpoint-done" data-action="checkpoint-done">TIẾP TỤC THỂ CHẤT & THANG DÂY →</button><button class="secondary" data-action="list">Xem lại 6 bài tập</button></section>`);if(!state.checkpointStarted){state.checkpointStarted=true;startCheckpoint();}updateCheckpoint();}
function startCheckpoint(){if(state.active||state.checkpointMs<=0)return;state.active=true;state.clock=performance.now();interval=setInterval(tick,100);updateCheckpoint();}
function updateCheckpoint(){if(state.view!=='checkpoint')return;document.querySelector('#checkpoint-clock').textContent=clockText(state.checkpointMs);document.querySelector('#checkpoint-progress').value=120000-state.checkpointMs;const toggle=document.querySelector('#checkpoint-toggle');toggle.hidden=state.checkpointMs===0;toggle.textContent=state.active?'⏸ TẠM DỪNG':'▶ TIẾP TỤC NGHỈ';document.querySelector('#checkpoint-done').disabled=state.checkpointMs>0;}
function announce(text){const el=document.querySelector('#timer-announcement');if(el)el.textContent=text;}
function notify(text){clearTimeout(toastTimer);document.querySelector('#toast-text').textContent=text;document.querySelector('#toast').classList.add('show');toastTimer=setTimeout(()=>document.querySelector('#toast').classList.remove('show'),6000);}
screen.addEventListener('click',event=>{const b=event.target.closest('button');if(!b||b.disabled)return;if(b.dataset.open!==undefined)return detail(Number(b.dataset.open));switch(b.dataset.action){case'intro':return intro();case'list':return list();case'continue':return completedCount()===6?checkpoint():detail(state.items.findIndex(s=>s.sets<2));case'start':return start();case'count':return count();case'pause':stop();return renderPlayer();case'next':return next();case'rest-toggle':if(state.active)stop();else startRest();return updateRest();case'rest-continue':if(item().restMs===0){detail(state.index);start();}return;case'checkpoint-toggle':if(state.active)stop();else startCheckpoint();return updateCheckpoint();case'checkpoint-done':if(state.checkpointMs===0)window.location.href='strength.html';return;}});
screen.addEventListener('change',event=>{if(event.target.id==='rest-select')state.restSeconds=Number(event.target.value);if(event.target.id==='lap-select'){state.laps=Number(event.target.value);renderPlayer();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.active){stop();if(state.view==='detail')renderPlayer();else if(state.view==='rest')updateRest();else if(state.view==='checkpoint')updateCheckpoint();notify('Đã tạm dừng khi bạn rời trang. Bấm Tiếp tục khi sẵn sàng.');}});
document.querySelector('#close-toast').addEventListener('click',()=>document.querySelector('#toast').classList.remove('show'));
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelector('#toast').classList.remove('show');});
intro();
