'use strict';
// Six exercises, in-memory session only. Viewing a 3D guide never changes counters or XP.
const exercises = [
  {
    name:'Side Kicks', translation:'Đá chân sang ngang', icon:'🦵', short:true, perSide:true, xp:30,
    dose:'5 lần/chân × 2 hiệp', placement:'Trên đầu gối khoảng 5 cm', goals:['Cơ hông','Đùi ngoài','Thăng bằng'],
    steps:['Đeo vòng dây trên hai đầu gối khoảng 5 cm, không đè lên khớp. Đứng thẳng; có thể vịn nhẹ vào tường hoặc điểm tựa chắc chắn.','Giữ chân trụ vững, đưa chân còn lại sang ngang trong tầm kiểm soát; mũi chân hướng trước, thân người không nghiêng theo.','Thu chân về chậm, không để dây bật lại. Thực hiện 5 lần chân trái, 5 lần chân phải để hoàn thành một hiệp.'],
    avoid:['Đeo dây ngay khớp gối','Nghiêng thân hoặc dùng đà để kéo dây'], correct:['Dây nằm trên gối khoảng 5 cm','Chân trụ vững, dùng lực cản vừa sức']
  },
  {
    name:'Hip Flexion', translation:'Gập hông / nâng gối', icon:'⬆️', short:true, perSide:true, xp:30,
    dose:'5 lần/chân × 2 hiệp', placement:'Vòng qua mu hai bàn chân, mang giày', goals:['Cơ gập hông','Đùi trước','Kiểm soát bước chạy'],
    steps:['Mang giày, đặt vòng dây qua hai bàn chân ở vùng mu chân. Đứng gần điểm tựa; giáo viên kiểm tra dây không dễ trượt khỏi mũi chân.','Trụ một chân, nâng gối chân kia chậm về phía trước đến độ cao vừa sức; giữ thân người thẳng.','Hạ chân có kiểm soát. Tập 5 lần chân trái rồi 5 lần chân phải trong mỗi hiệp.'],
    avoid:['Đặt dây sát đầu mũi giày, dễ tuột','Ngả người ra sau để cố nâng gối'],correct:['Kiểm tra vị trí dây và giày trước khi tập','Nâng–hạ chậm, giữ thăng bằng']
  },
  {
    name:'Nhón gót chân với dây', translation:'Calf Raise Band', icon:'🦶', short:true, xp:25,
    dose:'5 lần × 2 hiệp', placement:'Trên đầu gối khoảng 5 cm', goals:['Cơ bắp chân','Kiểm soát cổ chân'],
    steps:['Đeo dây trên gối khoảng 5 cm, hai chân mở tự nhiên, gối cùng hướng mũi chân. Có thể vịn điểm tựa chắc chắn.','Nhón hai gót từ từ, giữ hai chân ổn định và không để gối xụm vào trong.','Hạ gót có kiểm soát; nâng và hạ trọn vẹn tính là 1 lần. Thực hiện 5 lần mỗi hiệp.'],
    avoid:['Khóa gối hoặc đổ cổ chân sang bên','Nhún bật, hạ gót đột ngột'],correct:['Giữ hướng gối và cổ chân ổn định','Dây ở đùi hỗ trợ giữ hướng chân; không tạo lực cản trực tiếp lên động tác nhón gót']
  },
  {
    name:'Nâng cao đùi với dây', translation:'Band High Knee', icon:'🏃', short:true, perSide:true, xp:30,
    dose:'5 lần/chân × 2 hiệp', placement:'Vòng qua mu hai bàn chân, mang giày', goals:['Nhịp chân','Cơ hông','Phối hợp vận động'],
    steps:['Mang giày, đặt dây chắc ở vùng mu hai bàn chân. Giữ thân người thẳng và kiểm tra khoảng trống quanh người.','Nâng gối từng chân với biên độ vừa sức, phối hợp tay đối bên; hạ chân nhẹ nhàng và giữ dây trong tầm kiểm soát.','Ở bản tập này, hoàn thành 5 lần chân trái rồi đổi sang 5 lần chân phải. Ưu tiên kiểm soát trước khi tăng nhịp.'],
    avoid:['Giật chân nhanh làm dây tuột','Ngả người ra sau hoặc mất thăng bằng'],correct:['Dây không trượt khỏi giày','Duy trì lực nhẹ, không chạy nước rút với dây ngắn ở chân']
  },
  {
    name:'Squat gánh dây kháng lực', translation:'Band Squat · Tay giữ dây ngang hông', icon:'🏋️', xp:45, configurable:'squat',
    dose:'5–8 lần × 2 hiệp', placement:'Hai chân đứng giữa dây; tay giữ hai bên ngang hông', goals:['Đùi, mông','Sức mạnh thân dưới'],
    steps:['Đứng lên đoạn giữa dây bằng hai chân, đặt dây dưới phần giữa đế giày; tay nắm hai bên ngang hông. Chọn độ căng theo hướng dẫn của giáo viên.','Đưa hông ra sau và hạ Squat tới độ sâu thoải mái. Giữ gót vững, lưng trung tính và gối cùng hướng mũi chân.','Đẩy người đứng lên có kiểm soát, tay vẫn giữ dây thấp. Thực hiện 5–8 lần mỗi hiệp theo lựa chọn.'],
    avoid:['Vắt dây qua vai hoặc cổ','Để dây ép lên cột sống','Tiếp tục khi gối xụm vào trong: dừng ngay để điều chỉnh'],correct:['Hai chân giữ đoạn giữa dây chắc chắn','Tay giữ thấp; không cố kéo quá giới hạn dây'],schedule:true
  },
  {
    name:'Band-Resisted Sprint', translation:'Bứt tốc kéo dây', icon:'⚡', xp:60, configurable:'sprint',
    dose:'5 lượt × 1–2 hiệp', placement:'Vòng tại vùng hông; người hỗ trợ giữ phía sau', goals:['Tốc độ','Sức mạnh bứt phá','Phối hợp chạy'],
    steps:['Chỉ dùng dây hoặc bộ đai được nhà sản xuất cho phép cho bài chạy kháng lực. Giáo viên bố trí người hỗ trợ và đoạn chạy 3–5 m; đai nằm ở hông, không ép bụng hay cổ.','Người hỗ trợ giữ lực nhẹ, di chuyển cùng khi cần để không kéo quá giới hạn dây. Người tập chạy tới mốc trong kiểm soát; không neo cố định dây dài 1,04 m để kéo giãn thêm 3–5 m.','Giảm tốc, cùng người hỗ trợ thả lực từ từ rồi đi bộ về vạch. Một lượt đi–về và sẵn sàng tại vạch được xác nhận là 1 lượt; thực hiện 5 lượt mỗi hiệp.'],
    avoid:['Thả tay đột ngột khi dây đang căng','Dùng dây hỏng hoặc kéo vượt giới hạn của nhà sản xuất','Tập một mình, dây quấn cổ hoặc ép bụng'],correct:['Có giáo viên và người hỗ trợ giữ lực nhẹ','Dùng dụng cụ phù hợp bài chạy; không mặc định dây 1,04 m nào cũng phù hợp']
  }
];
const state = {view:'intro',index:0,restSeconds:60,totalMs:0,active:false,clock:0,
  items:exercises.map((e,i)=>({sets:0,setTarget:i===5?1:2,reps:5,count:0,sides:[0,0],side:0,started:false,restMs:0,restTotal:0,distance:3,day:'T4'}))};
const screen=document.querySelector('#screen');
let interval=null,toastTimer=null;
const current=()=>state.items[state.index];
const exercise=()=>exercises[state.index];
const completed=i=>state.items[i].sets===state.items[i].setTarget;
const completedCount=()=>exercises.filter((_,i)=>completed(i)).length;
const xp=()=>exercises.reduce((sum,e,i)=>sum+(completed(i)?e.xp:0),0);
const setTotal=()=>state.items.reduce((sum,s)=>sum+s.setTarget,0);
const setDone=()=>state.items.reduce((sum,s)=>sum+s.sets,0);
const pad=n=>String(n).padStart(2,'0');
const formatTime=ms=>`${pad(Math.floor(Math.ceil(ms/1000)/60))}:${pad(Math.ceil(ms/1000)%60)}`;
const back=()=>'<button class="back" data-action="list">← Danh sách bài tập</button>';
function progress(){return `<div class="module-progress"><div><span>${completedCount()}/6 bài hoàn thành</span><b>${setDone()}/${setTotal()} hiệp</b></div><progress value="${setDone()}" max="${setTotal()}" aria-label="Đã hoàn thành ${setDone()} trên ${setTotal()} hiệp"></progress></div>`;}
function equipment(){return `<div class="equipment-grid"><div class="equipment"><span class="band-mark" aria-hidden="true"></span><div><b>Dây ngắn · 25–30 cm</b><p>Nhãn lực cản: 15 kg<br>4 bài tập · Cần chọn lực vừa sức</p></div></div><div class="equipment long"><span class="band-mark" aria-hidden="true"></span><div><b>Dây dài · 1,04 m</b><p>2 bài tập · Kiểm tra công dụng<br>và giới hạn giãn của sản phẩm</p></div></div></div>`;}
function safetyNote(){return `<div class="band-safe-note"><strong>⚠ Chọn dây theo khả năng, ưu tiên đúng động tác</strong><p>15 kg là thông số nhãn dây trong bản thiết kế, không phải mức lực mặc định cho mọi học sinh. Giáo viên chọn lực nhẹ phù hợp; kiểm tra dây rách, nứt hoặc trượt trước khi tập. Không thả dây bật lại, không kéo quá giới hạn nhà sản xuất. Dừng nếu đau.</p><div class="band-links"><a href="https://www.healthychildren.org/English/news/Pages/Guidance-on-Resistance-Training-for-Children.aspx" target="_blank" rel="noopener noreferrer">Hướng dẫn tập cho trẻ · AAP ↗</a><a href="https://www.theraband.com/care-and-safety" target="_blank" rel="noopener noreferrer">Chăm sóc dây · THERABAND ↗</a></div></div>`;}
function render(html){screen.innerHTML=html;document.querySelector('#earned').textContent=`${xp()} / 220 XP`;window.scrollTo({top:0,behavior:'instant'});const h=screen.querySelector('h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}}
function intro(){stop();state.view='intro';render(`<a class="back" href="index.html">← Quay lại trang chủ</a><section class="intro-card"><div class="intro-symbol">🪢</div><span class="module-label">RESISTANCE BAND TRAINING</span><h1>DÂY KHÁNG LỰC</h1><p class="subtitle">Tăng sức mạnh · Tăng tốc độ<br>Tăng khả năng bứt phá</p><p class="description">Tăng sức mạnh chân, cơ hông, khả năng kiểm soát cơ thể, sức bật và tốc độ bứt phá.</p><div class="intro-stats"><div><b>🔥 6 bài tập</b><span>2 nhóm dây</span></div><div><b>⏱ 10–15 phút</b><span>Thời lượng dự kiến</span></div><div><b>💪 Intermediate</b><span>Ưu tiên kiểm soát</span></div></div>${equipment()}<div class="rest-note">🔥 Chủ yếu 5 lần × 2 hiệp<br>⏸ Nghỉ 1–2 phút giữa hiệp · ⭐ Tổng 220 XP</div><button class="primary" data-action="list">▶ BẮT ĐẦU</button>${safetyNote()}</section>`);}
function cards(from,to){return `<div class="exercise-list">${exercises.slice(from,to).map((e,j)=>{const i=from+j,s=state.items[i];return `<article class="exercise-card ${completed(i)?'done':''}"><div class="exercise-top"><span class="sport-icon">${e.icon}</span><span class="exercise-number">${completed(i)?'✓ HOÀN THÀNH':`BÀI ${pad(i+1)}`}</span></div><h3>${e.name}<span class="exercise-translation">${e.translation}</span></h3><div class="exercise-meta-row"><div class="dose">${e.dose}</div><span class="xp-pill">⭐ +${e.xp} XP</span></div><div class="set-dots">${Array.from({length:s.setTarget},(_,k)=>`<span class="${s.sets>k?'checked':''}">${s.sets>k?'✓ ':''}Hiệp ${k+1}</span>`).join('')}</div><div class="band-placement">📍 Vị trí dây<strong>${e.placement}</strong></div>${e.schedule?'<div class="band-schedule">📅 Kế hoạch bài Squat: 1 buổi/tuần · T4 hoặc T7</div>':''}<ul>${e.goals.map(g=>`<li>${g}</li>`).join('')}</ul><button class="detail-button" data-open="${i}">${s.restMs>0?'⏱ TIẾP TỤC NGHỈ':'CHI TIẾT →'}</button></article>`;}).join('')}</div>`;}
function list(){stop();state.view='list';render(`<button class="back" data-action="intro">← Giới thiệu module</button><section class="module-hero"><span class="module-label">GIAI ĐOẠN 04 · INTERMEDIATE</span><h1>🟣 Dây kháng lực</h1><p>Kiểm soát lực dây. Vững vàng trong từng chuyển động.</p><div class="module-tags"><span>6 bài tập · 2 nhóm</span><span>⏱ Dự kiến 10–15 phút</span><span>⭐ Tổng 220 XP</span></div>${progress()}</section><div class="overview-line"><h2>Sẵn sàng cho từng hiệp</h2><label class="rest-setting">Nghỉ giữa hiệp<select id="rest-select">${[60,90,120].map(n=>`<option value="${n}" ${n===state.restSeconds?'selected':''}>${n===60?'1 phút':n===90?'1 phút 30 giây':'2 phút'}</option>`).join('')}</select></label></div><div class="group-heading"><span>🟢</span><div><h2>A. Dây ngắn</h2><p>25–30 cm · Nhãn 15 kg · Chọn lực phù hợp</p></div><b class="group-count">${state.items.slice(0,4).filter((_,i)=>completed(i)).length}/4 bài</b></div>${cards(0,4)}<div class="group-heading ladder-heading"><span>🟣</span><div><h2>B. Dây dài</h2><p>1,04 m · Dụng cụ phải phù hợp từng bài</p></div><b class="group-count">${[4,5].filter(completed).length}/2 bài</b></div>${cards(4,6)}<div class="launch-row"><button class="primary" data-action="continue">${completedCount()===6?'XEM KẾT QUẢ →':'▶ TIẾP TỤC BÀI CHƯA HOÀN THÀNH'}</button></div>${safetyNote()}`);}
function dose(){const e=exercise(),s=current();return e.perSide?'5 lần mỗi chân':state.index===5?`5 lượt · ${s.distance} m/lượt`:`${s.reps} lần`;}
function safetyBox(e){return `<div class="safety-box"><h2>⚠ AN TOÀN</h2><ul>${e.avoid.map(t=>`<li>❌ ${t}</li>`).join('')}${e.correct.map(t=>`<li class="correct">✅ ${t}</li>`).join('')}</ul></div>`;}
function detail(index){stop();state.index=index;if(current().restMs>0)return rest();state.view='detail';const e=exercise(),s=current();render(`${back()}<div class="detail-heading"><span class="sport-icon">${e.icon}</span><div><span class="module-label">BÀI ${pad(index+1)}/06 · ${e.short?'DÂY NGẮN':'DÂY DÀI'}</span><h1>${e.name}</h1><span class="exercise-translation">${e.translation}</span></div></div><div class="detail-grid"><div><motion-guide exercise="band-${index}"></motion-guide><section class="player"><div id="player-content"></div></section>${progress()}</div><section class="card instructions"><div class="params"><div><span>SỐ LẦN / QUÃNG CHẠY</span><strong id="dose-label">${dose()}</strong></div><div><span>HIỆP</span><strong id="sets-label">${Math.min(s.sets+1,s.setTarget)}/${s.setTarget}</strong></div><div><span>NGHỈ GIỮA HIỆP</span><strong>${formatTime(state.restSeconds*1000)}</strong></div></div><div class="band-placement">📍 Vị trí dây<strong>${e.placement}</strong></div><h2>Hướng dẫn thực hiện</h2><ol class="steps">${e.steps.map(t=>`<li>${t}</li>`).join('')}</ol>${e.schedule?`<div class="band-schedule">📅 Kế hoạch bài này: 1 buổi/tuần · <span id="schedule-day">${s.day==='T4'?'Thứ 4':'Thứ 7'}</span><br>Chỉ là lịch trong bản tập, chưa tạo lời nhắc.</div>`:''}${safetyBox(e)}</section></div>`);renderPlayer();}
function options(){const s=current(),e=exercise();if(s.started||s.sets||s.count||s.sides.some(Boolean)||!e.configurable)return '';return `<div class="strength-options">${e.configurable==='squat'?`<label>Số lần mỗi hiệp<select id="reps-select">${[5,6,7,8].map(n=>`<option value="${n}" ${n===s.reps?'selected':''}>${n} lần</option>`).join('')}</select></label><label>Buổi tập trong tuần<select id="day-select"><option value="T4" ${s.day==='T4'?'selected':''}>Thứ 4</option><option value="T7" ${s.day==='T7'?'selected':''}>Thứ 7</option></select></label>`:`<label>Số hiệp<select id="sets-select"><option value="1" ${s.setTarget===1?'selected':''}>1 hiệp</option><option value="2" ${s.setTarget===2?'selected':''}>2 hiệp</option></select></label><label>Quãng chạy mỗi lượt<select id="distance-select">${[3,4,5].map(n=>`<option value="${n}" ${s.distance===n?'selected':''}>${n} m</option>`).join('')}</select></label>`}</div>`;}
function renderPlayer(){const root=document.querySelector('#player-content');if(!root)return;const s=current(),e=exercise();if(completed(state.index)){root.innerHTML=`<div class="player-status">✓ HOÀN THÀNH ${s.setTarget}/${s.setTarget} HIỆP</div><div class="counter">+${e.xp}<span> XP</span></div><p class="phase">Đã nhận thưởng trong lượt tập này.</p><button class="primary" data-action="next">${completedCount()===6?'XEM KẾT QUẢ':'BÀI TIẾP THEO'} →</button>`;return;}
root.innerHTML=`<div class="step-state">Hiệp ${s.sets+1}/${s.setTarget} · ${state.active?'Đang tập':s.started?'Đã tạm dừng':'Sẵn sàng'}</div><div class="counter">${e.perSide?s.sides[s.side]:s.count}<span> / ${e.perSide?5:s.reps} ${state.index===5?'lượt':'lần'}</span></div><p class="phase" role="status">${e.perSide?`Đang tập: chân ${s.side===0?'TRÁI':'PHẢI'}`:state.index===5?`Mỗi lượt: chạy ${s.distance} m rồi đi bộ về vạch`:'Một chuyển động trọn vẹn tính là 1 lần'}</p>${e.perSide?`<div class="side-progress">${['Trái','Phải'].map((label,i)=>`<div class="${s.sides[i]===5?'complete':s.side===i?'current':''}">Chân ${label}<b>${s.sides[i]}/5 ${s.sides[i]===5?'✓':''}</b></div>`).join('')}</div>`:''}${options()}<div class="player-actions">${state.active?`<button class="primary" data-action="count">✓ ${state.index===5?'ĐÃ CHẠY & VỀ VẠCH':'XÁC NHẬN 1 LẦN'}</button><button class="secondary" data-action="pause">⏸ TẠM DỪNG</button>`:`<button class="primary" data-action="start">▶ ${s.started?'TIẾP TỤC':'BẮT ĐẦU'}</button>`}</div><p class="player-hint">${e.perSide?'Đủ 5 lần chân trái rồi đổi chân phải. Chỉ nghỉ giữa hiệp sau khi đủ cả hai chân.':'Bạn hoặc bạn tập cùng xác nhận sau mỗi lần hoàn thành.'} Hướng dẫn 3D có bộ điều khiển riêng.</p>`;}
function startClock(){if(state.active)return;state.active=true;state.clock=performance.now();interval=setInterval(tick,100);}
function halt(){state.active=false;clearInterval(interval);interval=null;}
function tick(){if(!state.active)return;const now=performance.now();let delta=Math.max(0,now-state.clock);state.clock=now;if(state.view==='rest'){delta=Math.min(delta,current().restMs);current().restMs=Math.max(0,current().restMs-delta);state.totalMs+=delta;if(current().restMs===0)halt();updateRest();}else if(state.view==='detail')state.totalMs+=delta;}
function stop(){if(state.active)tick();halt();}
function start(){if(state.view!=='detail'||state.active||completed(state.index))return;current().started=true;startClock();renderPlayer();}
function count(){if(state.view!=='detail'||!state.active||completed(state.index))return;tick();const s=current();if(exercise().perSide){s.sides[s.side]++;if(s.sides[0]===5&&s.sides[1]===5)return finishSet();if(s.sides[0]===5&&s.side===0){s.side=1;notify('Đủ 5 lần chân trái. Chuyển sang chân phải.');}}else{if(++s.count===s.reps)return finishSet();}renderPlayer();}
function finishSet(){stop();const s=current();if(completed(state.index))return;s.sets++;s.count=0;s.sides=[0,0];s.side=0;if(!completed(state.index)){s.restMs=state.restSeconds*1000;s.restTotal=s.restMs;return rest(true);}state.view='complete';render(`${back()}<section class="completion"><div class="celebrate">🎉</div><span class="module-label">KIỂM SOÁT TỐT TỪNG CHUYỂN ĐỘNG</span><h1>Hoàn thành<br>${exercise().name}</h1><div class="reward">⭐ +${exercise().xp} XP</div><p>Đủ ${s.setTarget}/${s.setTarget} hiệp${exercise().perSide?' · Cả hai chân':''}.</p>${progress()}<button class="primary" data-action="next">${completedCount()===6?'XEM KẾT QUẢ':'BÀI TIẾP THEO'} →</button></section>`);}
function rest(autoStart=false){stop();state.view='rest';render(`${back()}<section class="rest-screen"><span class="module-label">HOÀN THÀNH HIỆP ${current().sets}/${current().setTarget}</span><h1>⏸ Nghỉ giữa hiệp</h1><div class="rest-dial" id="rest-dial"><div><strong id="rest-clock"></strong><small>NGHỈ PHỤC HỒI</small></div></div><p class="rest-copy">Thả lỏng cơ thể · Đi bộ nhẹ<br>Uống nước nếu cần</p><div class="up-next">HIỆP TIẾP THEO<b>${exercise().name} · Hiệp ${current().sets+1}/${current().setTarget}</b></div><button class="primary" id="rest-continue" data-action="resume-set">TIẾP TỤC →</button><button class="secondary" id="rest-toggle" data-action="rest-toggle"></button><p class="timer-announcement" id="rest-status" role="status"></p></section>`);if(autoStart)startClock();updateRest();}
function updateRest(){if(state.view!=='rest')return;const s=current();document.querySelector('#rest-clock').textContent=formatTime(s.restMs);document.querySelector('#rest-dial').style.setProperty('--arc',`${s.restMs/Math.max(1,s.restTotal)*100}%`);document.querySelector('#rest-continue').disabled=s.restMs>0;const toggle=document.querySelector('#rest-toggle');toggle.hidden=s.restMs===0;toggle.textContent=state.active?'⏸ TẠM DỪNG ĐỒNG HỒ':'▶ TIẾP TỤC NGHỈ';const message=s.restMs===0?'Đã hết giờ nghỉ. Sẵn sàng cho hiệp tiếp theo.':state.active?'Đang nghỉ…':'Đồng hồ đang tạm dừng.';const el=document.querySelector('#rest-status');if(el.textContent!==message)el.textContent=message;}
function resumeSet(){if(state.view!=='rest'||current().restMs>0)return;stop();detail(state.index);start();}
function next(){if(completedCount()===6)return summary();let index=exercises.findIndex((_,i)=>i>state.index&&!completed(i));if(index<0)index=exercises.findIndex((_,i)=>!completed(i));detail(index);}
function summary(){if(completedCount()!==6)return list();stop();state.view='summary';render(`<a class="back" href="index.html">← Về trang chủ</a><section class="completion"><div class="celebrate">🏆</div><span class="module-label">RESISTANCE BAND TRAINING</span><h1>HOÀN THÀNH<br>DÂY KHÁNG LỰC</h1><div class="reward">⭐ +220 XP</div><div class="result-grid"><div><span>✅ Bài hoàn thành</span><strong>6/6</strong></div><div><span>⏱ Thời gian thực tế</span><strong>${formatTime(state.totalMs)}</strong></div></div><div class="reward-breakdown">🔥 <b>Streak +1</b> · Minh họa<br>💪 ${setDone()}/${setTotal()} hiệp đã hoàn thành</div><p class="stop-note">Thời gian theo phút:giây, gồm tập và nghỉ; không tính lúc tạm dừng hay xem mô phỏng trước khi tập.</p><div class="finish-progress"><p>📈 Hoàn thành module Dây kháng lực</p><progress value="100" max="100" aria-label="Module hoàn thành 100%"></progress><small>Phần thưởng chỉ tính một lần trong lượt mở trang này.</small></div><p class="band-recovery">Thả lỏng và thu dọn dây cùng giáo viên.<br>Bạn đã hoàn thành phần luyện tập này.</p><a class="primary" href="index.html">VỀ TRANG CHỦ →</a><button class="secondary" data-action="list">Xem lại 6 bài tập</button></section>`);}
function notify(text){clearTimeout(toastTimer);document.querySelector('#toast-text').textContent=text;document.querySelector('#toast').classList.add('show');toastTimer=setTimeout(()=>document.querySelector('#toast').classList.remove('show'),5500);}
screen.addEventListener('click',event=>{const b=event.target.closest('button');if(!b||b.disabled)return;if(b.dataset.open!==undefined)return detail(Number(b.dataset.open));switch(b.dataset.action){case'intro':return intro();case'list':return list();case'continue':return completedCount()===6?summary():detail(exercises.findIndex((_,i)=>!completed(i)));case'start':return start();case'count':return count();case'pause':stop();return renderPlayer();case'next':return next();case'rest-toggle':if(state.active)stop();else if(current().restMs>0)startClock();return updateRest();case'resume-set':return resumeSet();}});
screen.addEventListener('change',event=>{const el=event.target,s=current();if(el.id==='rest-select'){const n=Number(el.value);if([60,90,120].includes(n))state.restSeconds=n;return;}if(s.started||s.sets||s.count||s.sides.some(Boolean))return;if(el.id==='reps-select'&&state.index===4&&[5,6,7,8].includes(Number(el.value)))s.reps=Number(el.value);else if(el.id==='day-select'&&state.index===4&&['T4','T7'].includes(el.value))s.day=el.value;else if(el.id==='sets-select'&&state.index===5&&[1,2].includes(Number(el.value)))s.setTarget=Number(el.value);else if(el.id==='distance-select'&&state.index===5&&[3,4,5].includes(Number(el.value)))s.distance=Number(el.value);else return;renderPlayer();document.querySelector('#dose-label').textContent=dose();document.querySelector('#sets-label').textContent=`${s.sets+1}/${s.setTarget}`;const schedule=document.querySelector('#schedule-day');if(schedule)schedule.textContent=s.day==='T4'?'Thứ 4':'Thứ 7';const bar=document.querySelector('.module-progress');if(bar)bar.outerHTML=progress();});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.active){stop();if(state.view==='detail')renderPlayer();else if(state.view==='rest')updateRest();notify('Đã tạm dừng khi rời trang. Bấm Tiếp tục khi sẵn sàng.');}});
document.querySelector('#close-toast').addEventListener('click',()=>document.querySelector('#toast').classList.remove('show'));
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelector('#toast').classList.remove('show');});
intro();
