'use strict';
// Module độc lập: dữ liệu bài tập và trạng thái trong bộ nhớ, không dùng database.
const exercises = [
  {name:'Nhảy bật cao',icon:'⬆️',dose:'5 lần × 2 hiệp',reps:5,xp:30,goals:['Sức bật','Cơ chân'],steps:['Đứng hai chân rộng bằng hông, giữ khoảng trống xung quanh.','Hơi gập hông và gối, đánh tay và bật thẳng lên với độ cao vừa sức.','Tiếp đất nhẹ bằng hai chân, gối mềm; ổn định rồi lặp lại, tổng 5 lần mỗi hiệp.'],errors:['Tiếp đất với gối khóa cứng','Gối đổ vào trong','Bật lần tiếp khi chưa giữ được thăng bằng']},
  {name:'Hít đất / Chống đẩy',icon:'💪',dose:'5 cái × 2 hiệp',reps:5,xp:35,goals:['Tay, ngực','Vai'],steps:['Hai tay chống rộng hơn vai một chút, đặt chân vững hoặc chống gối nếu cần giảm độ khó.','Giữ thân người thành một đường thẳng, siết nhẹ bụng.','Hạ ngực xuống vừa phải rồi đẩy lên, khuỷu tay hướng chéo về sau; một lần hạ–đẩy là 1 cái.'],errors:['Võng lưng','Hông nâng quá cao','Khuỷu tay xòe quá rộng']},
  {name:'Ngồi xổm (Squat)',icon:'🦵',dose:'5–8 cái hoặc giữ 30 giây × 2 hiệp',reps:5,xp:35,config:'squat',goals:['Đùi, mông','Thân dưới'],steps:['Đứng hai chân rộng bằng vai, mũi chân hướng tự nhiên, giữ gót trên sàn.','Đưa hông ra sau, gập gối hạ người tới độ sâu thoải mái, giữ gối cùng hướng mũi chân.','Theo số lần: đứng lên có kiểm soát, lặp 5–8 cái. Theo thời gian: giữ tư thế đã chọn trong 30 giây, thở đều.'],errors:['Nhấc gót chân','Gối đổ vào trong','Cong lưng hoặc hạ quá sâu']},
  {name:'Plank khuỷu tay',icon:'🧱',dose:'10–15 giây × 2 hiệp',seconds:10,xp:30,config:'plank',goals:['Cơ lõi, bụng','Ổn định lưng'],steps:['Đặt khuỷu tay dưới vai, cẳng tay trên thảm, duỗi chân và chống mũi chân.','Giữ đầu, thân và chân trên một đường thẳng, siết nhẹ bụng; có thể hạ gối để giảm độ khó.','Giữ 10–15 giây theo lựa chọn và thở đều, sau đó hạ gối nhẹ nhàng.'],errors:['Võng lưng','Nâng hông quá cao','Nín thở khi giữ tư thế']},
  {name:'Bench dips (bục thấp 8 cm)',icon:'🪑',dose:'5 cái × 2 hiệp',reps:5,xp:35,goals:['Tay sau','Vai'],steps:['Dùng bục cao khoảng 8 cm, chắc chắn, chống trượt; đặt hai tay ở mép bục, co gối và giữ bàn chân trên sàn.','Giữ hông sát bục, gập khuỷu tay nhẹ để hạ người trong biên độ nhỏ, không ép vai ra sau.','Đẩy tay trở về, thực hiện 5 cái; dừng nếu vai khó chịu và nhờ giáo viên điều chỉnh.'],errors:['Bục trượt hoặc không chắc chắn','Hạ quá sâu, ép vai','Đưa hông quá xa bục']},
  {name:'Nhảy dây',icon:'🪢',dose:'50 cái × 2 hiệp',reps:50,xp:40,goals:['Tim mạch','Phối hợp'],steps:['Chọn dây vừa tầm, đứng ở khoảng trống đủ rộng, kiểm tra mặt sân.','Xoay dây bằng cổ tay, bật thấp vừa đủ để dây đi qua dưới chân.','Tiếp đất nhẹ, duy trì nhịp đều; mỗi lần dây qua chân thành công tính là 1 cái, tổng 50 cái mỗi hiệp.'],errors:['Bật quá cao','Vung cả cánh tay','Tiếp đất nặng hoặc nhảy sát bạn khác']},
  {name:'Thang dây – Scissors taps',icon:'👣',dose:'4 vòng',ladder:true,xp:40,goals:['Nhịp chân','Phối hợp'],steps:['Trải thang dây phẳng trên sân; quan sát mẫu bước Scissors taps của giáo viên trước khi bắt đầu.','Luân phiên đổi vị trí hai chân theo nhịp cắt kéo của mẫu, bước nhẹ và tránh giẫm lên dây.','Đi hết chiều dài thang tính là 1 vòng; đi bộ về vạch xuất phát để nghỉ, thực hiện tổng 4 vòng.'],errors:['Giẫm vào dây thang','Đổi chân quá nhanh, mất nhịp','Chưa giữ thăng bằng đã tăng tốc']},
  {name:'Thang dây – Shuffle forward',icon:'↔️',dose:'4 vòng',ladder:true,xp:40,goals:['Linh hoạt','Tốc độ ngang'],steps:['Đứng tại đầu thang, gối hơi chùng; quan sát mẫu Shuffle forward của giáo viên.','Thực hiện bước di chuyển ngang theo mẫu kết hợp tiến dần dọc thang, giữ nhịp tay chân và thân người ổn định.','Đi hết thang tính là 1 vòng; đi bộ về vạch xuất phát để nghỉ, lặp đủ 4 vòng.'],errors:['Vội tăng tốc khi chưa đúng nhịp','Gối khóa cứng','Bước lên dây hoặc lệch khỏi ô']},
  {name:'Thang dây – Xoay háng vào ra',icon:'🔄',dose:'4 vòng',ladder:true,xp:40,goals:['Linh hoạt hông','Điều khiển cơ thể'],steps:['Đứng trước thang, thả lỏng gối và quan sát nhịp bước vào–ra của giáo viên.','Luân phiên bước vào và ra ô thang, xoay hông nhẹ theo hướng bước; để bàn chân chuyển theo, không vặn gối trên chân trụ cố định.','Di chuyển hết thang là 1 vòng; đi bộ trở về vạch xuất phát, thực hiện tổng 4 vòng.'],errors:['Vặn gối khi bàn chân cố định','Xoay hông quá mạnh','Bước quá rộng, mất thăng bằng']},
  {name:'Thang dây – Forward and 1 back',icon:'⏩',dose:'4 vòng',ladder:true,xp:45,goals:['Phản xạ','Kiểm soát nhịp chân'],steps:['Đứng ở đầu thang, quan sát số ô tiến trong mẫu Forward and 1 back do giáo viên quy định.','Tiến theo nhịp mẫu rồi lùi 1 ô; lặp chu kỳ để di chuyển dần đến cuối thang, kiểm soát vị trí chân.','Hoàn thành chiều dài thang là 1 vòng; đi bộ về vạch xuất phát để nghỉ, lặp đủ 4 vòng.'],errors:['Lùi quá nhanh, không kiểm soát ô chân','Nhầm nhịp tiến–lùi','Giẫm vào thang hoặc va vào bạn phía sau']}
];
const state={view:'intro',index:0,restSeconds:60,totalMs:0,active:false,clock:0,
  items:exercises.map(e=>({done:0,count:0,mode:e.seconds?'time':'reps',target:e.seconds||e.reps||1,remaining:(e.seconds||0)*1000,restMs:0,restTotal:0,walking:false,started:false}))};
const screen=document.querySelector('#screen');
let interval=null,toastTimer=null;
const current=()=>state.items[state.index];
const exercise=()=>exercises[state.index];
const units=e=>e.ladder?4:2;
const completed=i=>state.items[i].done===units(exercises[i]);
const completedCount=()=>exercises.filter((_,i)=>completed(i)).length;
const xp=()=>exercises.reduce((sum,e,i)=>sum+(completed(i)?e.xp:0),0);
const completedUnits=()=>state.items.reduce((sum,e)=>sum+e.done,0);
const pad=n=>String(n).padStart(2,'0');
const formatTime=ms=>`${pad(Math.floor(Math.ceil(ms/1000)/60))}:${pad(Math.ceil(ms/1000)%60)}`;
const back=()=>'<button class="back" data-action="list">← Danh sách bài tập</button>';
function progress(){return `<div class="module-progress"><div><span>${completedCount()}/10 bài hoàn thành</span><b>${completedUnits()}/28 hiệp & vòng</b></div><progress max="28" value="${completedUnits()}" aria-label="Đã hoàn thành ${completedUnits()} trong 28 hiệp và vòng"></progress></div>`;}
function render(html){screen.innerHTML=html;document.querySelector('#earned').textContent=`${xp()} / 370 XP`;window.scrollTo({top:0,behavior:'instant'});const title=screen.querySelector('h1');if(title){title.tabIndex=-1;title.focus({preventScroll:true});}}
function intro(){stop();state.view='intro';render(`<a class="back" href="index.html">← Quay lại trang chủ</a><section class="intro-card"><div class="intro-symbol">⚡</div><span class="module-label">FITQUEST · GIAI ĐOẠN 03</span><h1>PHẦN THỂ CHẤT<br>& THANG DÂY</h1><p class="subtitle">Rèn sức mạnh – tốc độ – phối hợp</p><p class="description">Phát triển sức mạnh, sức bền, độ nhanh, khả năng phối hợp và phản xạ vận động cho học sinh.</p><div class="intro-stats"><div><b>🔥 10 bài tập</b><span>2 nhóm vận động</span></div><div><b>⏱ 15–20 phút</b><span>Thời lượng dự kiến</span></div><div><b>💪 Intermediate</b><span>Trung bình – Khá</span></div></div><div class="rest-note">⏸ Thể chất cơ bản: nghỉ 1–2 phút giữa mỗi hiệp<br>👣 Thang dây: đi bộ về vạch xuất phát để nghỉ</div><button class="primary" data-action="list">▶ BẮT ĐẦU LUYỆN TẬP</button><div class="route-strip"><b>01 · Thể chất cơ bản</b><span>02 · Thang dây</span><span>⭐ 370 XP</span></div></section>`);}
function cards(from,to){return `<div class="exercise-list">${exercises.slice(from,to).map((e,j)=>{const i=from+j,s=state.items[i];return `<article class="exercise-card ${e.ladder?'ladder-card':''} ${completed(i)?'done':''}"><div class="exercise-top"><span class="sport-icon">${e.icon}</span><span class="exercise-number">${completed(i)?'✓ HOÀN THÀNH':`BÀI ${pad(i+1)}`}</span></div><h3>${e.name}</h3><div class="exercise-meta-row"><div class="dose">${e.dose}</div><span class="xp-pill">⭐ +${e.xp}</span></div><div class="set-dots">${Array.from({length:units(e)},(_,k)=>`<span class="${s.done>k?'checked':''}">${s.done>k?'✓ ':''}${e.ladder?'Vòng':'Hiệp'} ${k+1}</span>`).join('')}</div>${e.ladder?'<div class="ladder-rule">👣 Đi bộ về vạch xuất phát là nghỉ.<br>Không chia hiệp riêng.</div>':''}<ul>${e.goals.map(g=>`<li>${g}</li>`).join('')}</ul><button class="detail-button" data-open="${i}">${s.walking?'TIẾP TỤC VỀ VẠCH':s.restMs>0?'⏱ TIẾP TỤC NGHỈ':'CHI TIẾT →'}</button></article>`;}).join('')}</div>`;}
function list(){stop();state.view='list';render(`<button class="back" data-action="intro">← Giới thiệu module</button><section class="module-hero"><span class="module-label">GIAI ĐOẠN 03 · INTERMEDIATE</span><h1>🔴 Thể chất & Thang dây</h1><p>Mạnh mẽ trong từng động tác, nhịp nhàng trong từng bước chân.</p><div class="module-tags"><span>10 bài · 2 nhóm</span><span>⏱ Dự kiến 15–20 phút</span><span>⭐ Tổng 370 XP</span></div>${progress()}</section><div class="overview-line"><h2>Chọn bài để bắt đầu</h2><label class="rest-setting">Nghỉ giữa hiệp <select id="rest-select">${[60,90,120].map(n=>`<option value="${n}" ${n===state.restSeconds?'selected':''}>${n===60?'1 phút':n===90?'1 phút 30 giây':'2 phút'}</option>`).join('')}</select></label></div><div class="group-heading"><span>💪</span><div><h2>Nhóm 1 · Thể chất cơ bản</h2><p>6 bài tập · Mỗi bài 2 hiệp</p></div><b class="group-count">${state.items.slice(0,6).filter(s=>s.done===2).length}/6 bài</b></div>${cards(0,6)}<div class="group-heading ladder-heading"><span>👣</span><div><h2>Nhóm 2 · Thang dây</h2><p>4 bài tập · Mỗi bài 4 vòng</p></div><b class="group-count">${state.items.slice(6).filter(s=>s.done===4).length}/4 bài</b></div>${cards(6,10)}<div class="launch-row"><button class="primary" data-action="continue">${completedCount()===10?'XEM KẾT QUẢ →':'▶ TIẾP TỤC BÀI CHƯA HOÀN THÀNH'}</button></div>`);}
function dose(){const s=current(),e=exercise();return e.ladder?'1 lượt hết thang':s.mode==='time'?`${s.target} giây`:`${s.target} ${state.index===1||state.index===2||state.index===4||state.index===5?'cái':'lần'}`;}
function detail(index){stop();state.index=index;if(current().restMs>0)return rest();if(current().walking)return walk();state.view='detail';const e=exercise(),s=current();render(`${back()}<div class="detail-heading"><span class="sport-icon">${e.icon}</span><div><span class="module-label">BÀI ${pad(index+1)}/10 · ${e.ladder?'THANG DÂY':'THỂ CHẤT CƠ BẢN'}</span><h1>${e.name}</h1></div></div><div class="detail-grid"><div><motion-guide exercise="strength-${index}" variant="${s.mode}"></motion-guide><section class="player"><div id="player-content"></div></section>${progress()}</div><section class="card instructions"><div class="params"><div><span>KHỐI LƯỢNG</span><strong id="dose-label">${dose()}</strong></div><div><span>${e.ladder?'VÒNG':'HIỆP'}</span><strong>${Math.min(s.done+1,units(e))}/${units(e)}</strong></div><div><span>NGHỈ</span><strong>${e.ladder?'Đi bộ về vạch':formatTime(state.restSeconds*1000)}</strong></div></div><h2>Hướng dẫn thực hiện</h2><ol class="steps">${e.steps.map(t=>`<li>${t}</li>`).join('')}</ol><div class="mistakes"><h2>⚠ Lỗi thường gặp</h2><ul>${e.errors.map(t=>`<li>${t}</li>`).join('')}</ul></div>${e.ladder?'<p class="muted-detail">Nhịp bước cụ thể theo mẫu giáo viên; ưu tiên đúng động tác trước khi tăng tốc.</p>':''}</section></div>`);renderPlayer();}
function options(){const s=current(),e=exercise();if(s.started||s.done||s.count||!e.config)return '';if(e.config==='squat')return `<div class="strength-options"><label>Chế độ Squat<select id="mode-select"><option value="reps" ${s.mode==='reps'?'selected':''}>Theo số lần</option><option value="time" ${s.mode==='time'?'selected':''}>Giữ 30 giây</option></select></label>${s.mode==='reps'?`<label>Số cái mỗi hiệp<select id="target-select">${[5,6,7,8].map(n=>`<option value="${n}" ${s.target===n?'selected':''}>${n} cái</option>`).join('')}</select></label>`:''}</div>`;return `<div class="strength-options"><label>Thời gian mỗi hiệp<select id="target-select">${[10,11,12,13,14,15].map(n=>`<option value="${n}" ${s.target===n?'selected':''}>${n} giây</option>`).join('')}</select></label></div>`;}
function renderPlayer(){const el=document.querySelector('#player-content');if(!el)return;const e=exercise(),s=current();if(completed(state.index)){el.innerHTML=`<div class="player-status">✓ ${units(e)}/${units(e)} ${e.ladder?'VÒNG':'HIỆP'} HOÀN THÀNH</div><div class="counter">+${e.xp}<span> XP</span></div><p class="phase">Đã nhận XP trong lượt tập này.</p><button class="primary" data-action="next">${completedCount()===10?'XEM KẾT QUẢ':'BÀI TIẾP THEO'} →</button>`;return;}
el.innerHTML=`<div class="step-state">${e.ladder?'Vòng':'Hiệp'} ${s.done+1}/${units(e)} · ${state.active?'Đang tập':s.started?'Đã tạm dừng':'Sẵn sàng'}</div><div class="counter" id="counter">${e.ladder?`${s.done+1}<span> / 4 vòng</span>`:s.mode==='time'?`${Math.ceil(s.remaining/1000)}<span> giây</span>`:`${s.count}<span> / ${s.target}</span>`}</div><p class="phase">${e.ladder?'Đi hết chiều dài thang rồi xác nhận.':s.mode==='time'?'Giữ tư thế ổn định, thở đều.':'Mỗi chuyển động trọn vẹn tính là 1 lần.'}</p>${options()}<div class="player-actions">${!state.active?`<button class="primary" data-action="start">▶ ${s.started?'TIẾP TỤC':'BẮT ĐẦU'}</button>`:`${e.ladder||s.mode==='reps'?`<button class="primary" data-action="count">✓ ${e.ladder?'HOÀN THÀNH VÒNG':'XÁC NHẬN 1 LẦN'}</button>`:''}<button class="secondary" data-action="pause">⏸ TẠM DỪNG</button>`}</div><p class="player-hint">${e.ladder?'Sau mỗi vòng chưa phải vòng cuối, đi bộ về vạch để nghỉ.':s.mode==='time'?'Đồng hồ tự kết thúc hiệp.':'Bạn hoặc bạn tập cùng xác nhận số lần.'} ${!e.ladder?'Nghỉ 1–2 phút giữa hai hiệp.':''}</p>`;}
function startClock(){if(state.active)return;state.active=true;state.clock=performance.now();interval=setInterval(tick,100);}
function halt(){state.active=false;clearInterval(interval);interval=null;}
function stop(){if(state.active)tick();halt();}
function start(){if(state.view!=='detail'||state.active||completed(state.index))return;current().started=true;startClock();renderPlayer();}
function tick(){if(!state.active)return;const now=performance.now();let delta=Math.max(0,now-state.clock);state.clock=now;const s=current();if(state.view==='detail'&&s.mode==='time'&&!exercise().ladder){delta=Math.min(delta,s.remaining);s.remaining=Math.max(0,s.remaining-delta);state.totalMs+=delta;const el=document.querySelector('#counter');if(el)el.innerHTML=`${Math.ceil(s.remaining/1000)}<span> giây</span>`;if(s.remaining===0){halt();finishUnit();}}else if(state.view==='rest'){delta=Math.min(delta,s.restMs);s.restMs=Math.max(0,s.restMs-delta);state.totalMs+=delta;updateRest();if(s.restMs===0){halt();updateRest();announce('Hết giờ nghỉ. Bạn có thể bắt đầu hiệp tiếp theo.');}}else if(state.view==='detail'||state.view==='walk'){state.totalMs+=delta;}}
function count(){if(state.view!=='detail'||!state.active||completed(state.index))return;if(exercise().ladder){stop();return finishUnit();}if(current().mode!=='reps')return;tick();current().count++;if(current().count>=current().target)finishUnit();else document.querySelector('#counter').innerHTML=`${current().count}<span> / ${current().target}</span>`;}
function finishUnit(){stop();const s=current(),e=exercise();if(s.done>=units(e))return;s.done++;s.count=0;s.started=false;s.remaining=s.mode==='time'?s.target*1000:0;if(!completed(state.index)){if(e.ladder){s.walking=true;return walk(true);}s.restMs=state.restSeconds*1000;s.restTotal=s.restMs;return rest(true);}state.view='complete';render(`${back()}<section class="completion"><div class="celebrate">🎉</div><span class="module-label">${e.ladder?'4 VÒNG NHỊP NHÀNG':'HOÀN THÀNH 2 HIỆP'}</span><h1>${e.name}<br>Đã hoàn thành!</h1><div class="reward">⭐ +${e.xp} XP</div><p>Mỗi nỗ lực đều đưa bạn tiến lên.</p>${progress()}<button class="primary" data-action="next">${completedCount()===10?'XEM KẾT QUẢ':'BÀI TIẾP THEO'} →</button></section>`);}
function rest(autoStart=false){stop();state.view='rest';render(`${back()}<section class="rest-screen"><span class="module-label">HIỆP 1/2 ĐÃ HOÀN THÀNH</span><h1>⏸ NGHỈ GIỮA HIỆP</h1><div class="rest-dial" id="rest-dial"><div><strong id="rest-clock"></strong><small>THỜI GIAN PHỤC HỒI</small></div></div><div class="rest-copy">Thả lỏng cơ thể · Đi bộ nhẹ<br>Uống 1–2 ngụm nước nhỏ nếu cần</div><div class="up-next">HIỆP TIẾP THEO<b>${exercise().name} · Hiệp 2/2</b></div><div class="rest-actions"><button class="primary" data-action="resume-set">TIẾP TỤC NGAY →</button><button class="secondary" id="skip-rest" data-action="resume-set">BỎ QUA NGHỈ</button></div><button class="secondary" id="rest-toggle" data-action="rest-toggle"></button><p class="timer-announcement" id="timer-announcement" role="status"></p><p class="muted-detail">Có thể kết thúc nghỉ sớm khi bạn đã sẵn sàng.</p></section>`);if(autoStart)startClock();updateRest();}
function updateRest(){if(state.view!=='rest')return;const s=current();document.querySelector('#rest-clock').textContent=formatTime(s.restMs);document.querySelector('#rest-dial').style.setProperty('--arc',`${s.restMs/Math.max(1,s.restTotal)*100}%`);document.querySelector('#skip-rest').hidden=s.restMs===0;const toggle=document.querySelector('#rest-toggle');toggle.hidden=s.restMs===0;toggle.textContent=state.active?'⏸ TẠM DỪNG ĐỒNG HỒ':'▶ TIẾP TỤC ĐỒNG HỒ';}
function resumeSet(){if(state.view!=='rest')return;stop();current().restMs=0;detail(state.index);start();}
function walk(autoStart=false){stop();state.view='walk';render(`${back()}<section class="rest-screen walk-screen"><span class="module-label">VÒNG ${current().done}/4 ĐÃ HOÀN THÀNH</span><h1>Đi bộ về vạch xuất phát</h1><div class="walk-icon">👣</div><p class="rest-copy">Thả lỏng, đi bộ nhẹ về đầu thang.<br>Đây là thời gian nghỉ giữa hai vòng.</p><div class="up-next">SẮP TỚI<b>${exercise().name}<br>Vòng ${current().done+1}/4</b></div><button class="primary" data-action="arrived">✓ ĐÃ VỀ VẠCH · BẮT ĐẦU VÒNG MỚI</button><button class="secondary" id="walk-toggle" data-action="walk-toggle"></button><p class="muted-detail">Không áp dụng đồng hồ nghỉ 1–2 phút cho nhóm thang dây.</p></section>`);if(autoStart)startClock();updateWalk();}
function updateWalk(){if(state.view==='walk')document.querySelector('#walk-toggle').textContent=state.active?'⏸ TẠM DỪNG':'▶ TIẾP TỤC ĐI BỘ';}
function next(){if(completedCount()===10)return summary();let i=exercises.findIndex((_,i)=>i>state.index&&!completed(i));if(i<0)i=exercises.findIndex((_,i)=>!completed(i));detail(i);}
function summary(){if(completedCount()!==10)return list();stop();state.view='summary';render(`<a class="back" href="index.html">← Về trang chủ</a><section class="completion"><div class="celebrate">🏆</div><span class="module-label">BẠN ĐÃ CHINH PHỤC!</span><h1>HOÀN THÀNH PHẦN<br>THỂ CHẤT & THANG DÂY</h1><div class="reward">⭐ +370 XP</div><div class="result-grid"><div><span>✅ Bài hoàn thành</span><strong>10/10</strong></div><div><span>⏱ Thời gian thực tế</span><strong>${formatTime(state.totalMs)}</strong></div></div><div class="reward-breakdown">💪 Cường độ: <b>Trung bình – Khá</b><br>🔥 <b>Streak +1</b> · Minh họa</div><p class="stop-note">Thời gian theo phút:giây, gồm tập và nghỉ đã thực hiện, không tính lúc tạm dừng.</p><div class="finish-progress"><p>📈 Đã hoàn thành thêm một phần của buổi tập</p><progress value="100" max="100" aria-label="Module Thể chất và Thang dây hoàn thành 100%"></progress><small>Module này: 100% · 12 hiệp thể chất + 16 vòng thang dây</small></div><div class="next-module">CHUẨN BỊ CHUYỂN SANG<strong>BÀI TẬP VỚI DÂY KHÁNG LỰC</strong>6 bài tập · Dây ngắn và dây dài · Hướng dẫn chuyển động 3D.</div><button class="primary" data-action="resistance">TIẾP TỤC →</button><button class="secondary" data-action="list">Xem lại bài tập</button></section>`);}
function announce(text){const el=document.querySelector('#timer-announcement');if(el)el.textContent=text;}
function notify(text){clearTimeout(toastTimer);document.querySelector('#toast-text').textContent=text;document.querySelector('#toast').classList.add('show');toastTimer=setTimeout(()=>document.querySelector('#toast').classList.remove('show'),6500);}
screen.addEventListener('click',event=>{const b=event.target.closest('button');if(!b||b.disabled)return;if(b.dataset.open!==undefined)return detail(Number(b.dataset.open));switch(b.dataset.action){case'intro':return intro();case'list':return list();case'continue':return completedCount()===10?summary():detail(exercises.findIndex((_,i)=>!completed(i)));case'start':return start();case'count':return count();case'pause':stop();return renderPlayer();case'next':return next();case'rest-toggle':if(state.active)stop();else if(current().restMs>0)startClock();return updateRest();case'resume-set':return resumeSet();case'walk-toggle':if(state.active)stop();else startClock();return updateWalk();case'arrived':if(state.view==='walk'){stop();current().walking=false;detail(state.index);start();}return;case'resistance':window.location.href='resistance.html';return;}});
screen.addEventListener('change',event=>{const s=current(),el=event.target;if(el.id==='rest-select'){state.restSeconds=Number(el.value);return;}if(s.started||s.done||s.count)return;if(el.id==='mode-select'){s.mode=el.value;s.target=s.mode==='time'?30:5;s.remaining=s.mode==='time'?30000:0;}else if(el.id==='target-select'){s.target=Number(el.value);s.remaining=s.mode==='time'?s.target*1000:0;}else return;renderPlayer();document.querySelector('#dose-label').textContent=dose();document.querySelector('motion-guide')?.setAttribute('variant',s.mode);});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.active){stop();if(state.view==='detail')renderPlayer();else if(state.view==='rest')updateRest();else if(state.view==='walk')updateWalk();notify('Đã tạm dừng khi rời trang. Bấm Tiếp tục khi bạn sẵn sàng.');}});
document.querySelector('#close-toast').addEventListener('click',()=>document.querySelector('#toast').classList.remove('show'));
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelector('#toast').classList.remove('show');});
intro();
