'use strict';
// Chỉ có module Khởi động nhẹ. Trạng thái trong bộ nhớ, không có database.
const exercises = [
 {name:'Quay tay + quay vai',icon:'🔄',dose:'10 lần tiến + 10 lần lùi',reps:20,goals:['Làm nóng khớp vai','Tăng khả năng vận động tay'],steps:['Đứng thẳng, hai chân mở rộng bằng vai, thả lỏng vai.','Đưa tay xoay vòng về phía trước 10 lần, giữ biên độ thoải mái.','Đổi chiều xoay ngược lại 10 lần, giữ thân người ổn định.'],errors:['Vai nâng quá cao','Lưng cong','Xoay tay quá nhanh'],phase:n=>n<10?`Xoay về phía trước · ${n}/10 lần`:`Xoay về phía sau · ${n-10}/10 lần`},
 {name:'Vươn người trái/phải',icon:'↔️',dose:'5 lần mỗi bên',reps:10,goals:['Kéo giãn thân người','Làm nóng vùng hông'],steps:['Đứng hai chân rộng bằng vai, giữ lưng thẳng và đầu gối thả lỏng.','Đưa tay phải lên cao, nghiêng thân nhẹ sang trái rồi trở về; thực hiện 5 lần.','Đổi tay, nghiêng thân nhẹ sang phải rồi trở về; thực hiện 5 lần, thở đều.'],errors:['Nghiêng người quá sâu hoặc giật mạnh','Xoay thân thay vì nghiêng sang bên','Nín thở khi vươn người'],phase:n=>n<5?`Nghiêng sang trái · ${n}/5 lần`:`Nghiêng sang phải · ${n-5}/5 lần`},
 {name:'Chạy bước nhỏ tại chỗ',icon:'🏃',dose:'30 giây',seconds:30,goals:['Tăng nhịp tim','Kích hoạt cơ chân'],steps:['Đứng thẳng, hai chân mở tự nhiên, khuỷu tay co nhẹ.','Chạy bước nhỏ tại chỗ, nhấc chân thấp và tiếp đất nhẹ, phối hợp đánh tay.','Duy trì nhịp thoải mái trong 30 giây, thở đều và nhìn về phía trước.'],errors:['Dậm chân quá mạnh','Gồng vai hoặc nín thở','Tăng tốc đột ngột'],phase:()=> 'Bước nhỏ, tiếp đất nhẹ, thở đều'},
 {name:'Tách 2 chân + xoay đầu gối',icon:'🔄',dose:'10 lần',reps:10,goals:['Làm nóng khớp gối','Tăng linh hoạt chân'],steps:['Tách hai chân vừa phải, mũi chân hướng tự nhiên, gập nhẹ đầu gối.','Đặt tay nhẹ lên đùi gần gối, thực hiện chuyển động vòng nhỏ và chậm trong phạm vi thoải mái; không vặn ép khớp.','Thực hiện tổng 10 vòng: 5 vòng một chiều, 5 vòng đổi chiều; giữ bàn chân ổn định.'],errors:['Xoay vòng quá rộng hoặc ép gối','Gập gối quá sâu','Tiếp tục khi thấy đau hoặc khó chịu'],phase:n=>n<5?`Vòng nhỏ · ${n}/5 lần chiều đầu`:`Đổi chiều · ${n-5}/5 lần`},
 {name:'Vỗ tay qua háng (Bước cao chân)',icon:'🙌',dose:'20 lần',reps:20,goals:['Phối hợp tay chân','Tăng khả năng vận động'],steps:['Đứng thẳng, hai chân mở tự nhiên, giữ thăng bằng.','Nâng một gối lên phía trước vừa sức, vỗ hai tay dưới đùi chân đang nâng rồi hạ chân nhẹ nhàng.','Đổi chân luân phiên, tổng 20 lần (10 lần mỗi chân); mỗi lần nâng và hạ một chân tính là 1 lần.'],errors:['Cúi gập lưng để vỗ tay','Nâng chân quá cao, mất thăng bằng','Hạ chân quá mạnh'],phase:n=>`Luân phiên hai chân · Lần tiếp theo: chân ${n%2===0?'trái':'phải'}`},
 {name:'Gót chạm mông',icon:'🦵',dose:'30 giây',seconds:30,goals:['Kích hoạt cơ đùi sau','Chuẩn bị chạy'],steps:['Đứng thẳng, mắt nhìn về trước, tay co nhẹ hai bên.','Luân phiên co gối đưa gót chân về phía mông, giữ hai gối hướng xuống và tiếp đất nhẹ.','Duy trì 30 giây với nhịp vừa sức; không cần ép gót chạm mông nếu chưa thoải mái.'],errors:['Ưỡn lưng hoặc đổ người ra trước','Giật chân quá mạnh','Nín thở hoặc tiếp đất nặng'],phase:()=> 'Luân phiên chân, giữ thân người ổn định'}
];
const state={index:0,view:'list',completed:new Set(),reps:0,remaining:30000,active:false,started:false,clock:0,totalMs:0,bonus:false};
const screen=document.querySelector('#screen');
let ticker=null, toastTimer=null;
const pad=n=>String(n).padStart(2,'0');
const totalXP=()=>state.completed.size*10+(state.bonus?10:0);
const backButton=()=>'<button class="back" data-action="list">← Quay lại danh sách</button>';
function progress(){return `<div class="module-progress"><div><span>Tiến độ khởi động nhẹ</span><b>${state.completed.size}/6 bài</b></div><progress value="${state.completed.size}" max="6" aria-label="Đã hoàn thành ${state.completed.size} trên 6 bài"></progress></div>`;}
function repaint(html){screen.innerHTML=html;document.querySelector('#earned').textContent=`${totalXP()} XP`;window.scrollTo({top:0,behavior:'instant'});const heading=screen.querySelector('h1');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}}
function list(){pause();state.view='list';repaint(`<a class="back" href="index.html">← Quay lại trang chủ</a><section class="module-hero"><span class="module-label">CHUẨN BỊ CHO MỌI CHUYỂN ĐỘNG</span><h1>🟢 Khởi động nhẹ</h1><p>Tập liên tục không nghỉ để làm nóng cơ thể, tăng nhiệt độ cơ, làm trơn các khớp và chuẩn bị cho buổi tập chính.</p><div class="module-tags"><span>▥ Beginner</span><span>◷ Dự kiến 5–7 phút</span><span>🔥 Tập liên tục</span><span>⏸ Không nghỉ giữa các bài</span></div></section><div class="overview-line"><h2>6 bài tập · Một khởi đầu tốt</h2><span>${state.completed.size}/6 hoàn thành</span></div><div class="exercise-list">${exercises.map((e,i)=>`<article class="exercise-card ${state.completed.has(i)?'done':''}"><div class="exercise-top"><span class="sport-icon">${e.icon}</span><span class="exercise-number">${state.completed.has(i)?'✓ ĐÃ XONG':`BÀI ${pad(i+1)}`}</span></div><h3>${e.name}</h3><div class="dose">${e.dose}<small>${e.reps?'1 hiệp':'Theo thời gian'}</small></div><ul>${e.goals.map(g=>`<li>${g}</li>`).join('')}</ul><button class="detail-button" data-open="${i}">▶ XEM CHI TIẾT</button></article>`).join('')}</div><div class="launch-row"><button class="primary" data-action="continue">${state.completed.size===6?'XEM KẾT QUẢ →':state.completed.size?'TIẾP TỤC KHỞI ĐỘNG →':'▶ BẮT ĐẦU KHỞI ĐỘNG'}</button></div>${progress()}`);}
function detail(index){pause();if(index!==state.index||state.view!=='detail'){state.reps=0;state.remaining=30000;state.started=false;}state.index=index;state.view='detail';const e=exercises[index];repaint(`${backButton()}<div class="detail-heading"><span class="sport-icon">${e.icon}</span><div><span class="module-label">BÀI ${pad(index+1)}/06</span><h1>${e.name}</h1></div></div><div class="detail-grid"><div><motion-guide exercise="warmup-${index}"></motion-guide><section class="player" aria-label="Điều khiển bài tập"><div id="player-content"></div></section>${progress()}</div><section class="card instructions"><div class="params"><div><span>${e.seconds?'THỜI GIAN':'SỐ LẦN'}</span><strong>${e.dose}</strong></div><div><span>HIỆP</span><strong>1/1</strong></div></div><h2>Hướng dẫn động tác</h2><ol class="steps">${e.steps.map(s=>`<li>${s}</li>`).join('')}</ol><div class="mistakes"><h2>⚠ Lỗi thường gặp</h2><ul>${e.errors.map(s=>`<li>${s}</li>`).join('')}</ul></div></section></div>`);renderPlayer();}
function renderPlayer(){const el=document.querySelector('#player-content');if(!el)return;const e=exercises[state.index];const done=state.completed.has(state.index);el.innerHTML=done?`<span class="player-status">✓ BÀI TẬP ĐÃ HOÀN THÀNH</span><div class="counter">+10 <span>XP</span></div><p class="phase">Đã ghi nhận trong lượt tập này.</p><button class="primary" data-action="next">TIẾP THEO →</button>`:`<div class="player-status">${state.active?'ĐANG TẬP':state.started?'ĐÃ TẠM DỪNG':'SẴN SÀNG CHƯA?'}</div><div class="counter" id="counter">${e.seconds?`${pad(Math.ceil(state.remaining/1000))}<span> giây</span>`:`${state.reps}<span> / ${e.reps} lần</span>`}</div><div class="phase" id="phase">${e.phase(state.reps)}</div><div class="player-actions">${!state.active?`<button class="primary" data-action="start">▶ ${state.started?'TIẾP TỤC':'BẮT ĐẦU'}</button>`:`${e.reps?'<button class="primary" data-action="rep">✓ XÁC NHẬN 1 LẦN</button>':''}<button class="secondary" data-action="pause">⏸ TẠM DỪNG</button>`}</div><p class="player-hint">${e.reps?'Sau mỗi lần thực hiện, bấm xác nhận hoặc nhờ bạn tập cùng đếm.':'Đồng hồ tự kết thúc sau 30 giây tập.'} Không có thời gian nghỉ tự động.</p>`;}
function tick(){if(!state.active)return;const now=performance.now();let delta=Math.max(0,now-state.clock);state.clock=now;if(exercises[state.index].seconds){delta=Math.min(delta,state.remaining);state.remaining=Math.max(0,state.remaining-delta);}state.totalMs+=delta;if(exercises[state.index].seconds){const counter=document.querySelector('#counter');if(counter)counter.innerHTML=`${pad(Math.ceil(state.remaining/1000))}<span> giây</span>`;if(state.remaining<=0)complete();}}
function pause(){if(state.active)tick();state.active=false;clearInterval(ticker);ticker=null;}
function start(){if(state.active||state.completed.has(state.index))return;state.active=true;state.started=true;state.clock=performance.now();renderPlayer();ticker=setInterval(tick,100);}
function rep(){if(!state.active||exercises[state.index].seconds)return;tick();state.reps++;if(state.reps>=exercises[state.index].reps)complete();else{document.querySelector('#counter').innerHTML=`${state.reps}<span> / ${exercises[state.index].reps} lần</span>`;document.querySelector('#phase').textContent=exercises[state.index].phase(state.reps);}}
function complete(){state.active=false;clearInterval(ticker);ticker=null;state.completed.add(state.index);state.view='complete';if(state.completed.size===6)state.bonus=true;repaint(`${backButton()}<section class="completion"><div class="celebrate">🎉</div><span class="module-label">THÊM MỘT BƯỚC TIẾN BỘ</span><h1>Hoàn thành!</h1><p>${exercises[state.index].name}</p><div class="reward">⭐ +10 XP</div>${progress()}<p>${state.completed.size===6?'Bạn đã hoàn thành đủ 6 động tác!':'Giữ nhịp vận động, chuyển ngay sang bài tiếp theo.'}</p><button class="primary" data-action="next">${state.completed.size===6?'XEM KẾT QUẢ':'TIẾP THEO'} →</button></section>`);}
function next(){if(state.completed.size===6)return summary();let index=exercises.findIndex((_,i)=>i>state.index&&!state.completed.has(i));if(index<0)index=exercises.findIndex((_,i)=>!state.completed.has(i));detail(index);}
function summary(){if(state.completed.size!==6)return list();pause();state.view='summary';const seconds=Math.floor(state.totalMs/1000);repaint(`<a class="back" href="index.html">← Về trang chủ</a><section class="completion"><div class="celebrate">🏆</div><span class="module-label">KHỞI ĐẦU THẬT TUYỆT!</span><h1>Hoàn thành<br>khởi động nhẹ</h1><p>Cơ thể đã vận động. Tinh thần đã sẵn sàng!</p><div class="reward">⭐ +70 XP</div><div class="result-grid"><div><span>✅ Bài tập hoàn thành</span><strong>6/6</strong></div><div><span>⏱ Thời gian tập thực tế</span><strong>${Math.floor(seconds/60)} phút ${pad(seconds%60)} giây</strong></div></div><div class="reward-breakdown">6 bài × 10 XP + 10 XP hoàn thành chương trình<br><br>🔥 Chuỗi luyện tập: <b>+1 ngày</b> (minh họa)</div><button class="primary" data-action="main-warmup">TIẾP TỤC KHỞI ĐỘNG CHÍNH →</button><p class="stop-note">Tiếp tục với 6 bài tập theo hiệp và nghỉ giữa hiệp.</p><button class="secondary" data-action="list">Xem lại 6 bài tập</button></section>`);}
function notify(message){clearTimeout(toastTimer);document.querySelector('#toast-text').textContent=message;document.querySelector('#toast').classList.add('show');toastTimer=setTimeout(()=>document.querySelector('#toast').classList.remove('show'),6000);}
screen.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;if(button.dataset.open!==undefined)return detail(Number(button.dataset.open));switch(button.dataset.action){case 'list':return list();case 'continue':return state.completed.size===6?summary():detail(exercises.findIndex((_,i)=>!state.completed.has(i)));case 'start':return start();case 'pause':pause();return renderPlayer();case 'rep':return rep();case 'next':return next();case 'main-warmup':window.location.href='main-warmup.html';return;}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.active){pause();renderPlayer();notify('Bài tập đã tạm dừng khi bạn rời trang. Bấm Tiếp tục khi sẵn sàng.');}});
document.querySelector('#close-toast').addEventListener('click',()=>document.querySelector('#toast').classList.remove('show'));
document.addEventListener('keydown',event=>{if(event.key==='Escape')document.querySelector('#toast').classList.remove('show');});
list();
